store-after/config/routes.rb
Store::Application.routes.draw do
  root to: 'products#index'
  resources :products
  resources :categories
end

store-after/app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products
end

store-after/app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  
  def category_name
    category.try(:name)
  end
  
  def category_name=(name)
    self.category = Category.find_or_create_by_name(name) if name.present?
  end
end

store-after/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

store-after/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.order(:name).where("name like ?", "%#{params[:term]}%")
    render json: @categories.map(&:name)
  end
end

store-after/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(params[:product])
    if @product.save
      redirect_to products_url, notice: "Successfully created product."
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(params[:product])
      redirect_to products_url, notice: "Successfully created product."
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_url, notice: "Successfully destroyed product."
  end
end

store-after/app/helpers/application_helper.rb
module ApplicationHelper
end

store-after/app/helpers/categories_helper.rb
module CategoriesHelper
end

store-after/app/helpers/products_helper.rb
module ProductsHelper
end

store-after/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Store</title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

store-after/app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :category_name %><br />
    <%= f.text_field :category_name, data: {autocomplete_source: categories_path} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

store-after/app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

store-after/app/views/products/index.html.erb
<h1>Products</h1>

<div id="products">
<% @products.each do |product| %>
  <div class="product">
    <h2><%= link_to product.name, product %></h2>
    <div class="details">
      <%= number_to_currency(product.price) %>
      <% if product.category %>
        | Category: <%= product.category.name %>
      <% end %>
      | <%= link_to "Edit", edit_product_path(product) %>
    </div>
  </div>
<% end %>
</div>

<p><%= link_to "New Product", new_product_path %></p>

store-after/app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

store-after/app/views/products/show.html.erb
<p>
  <b>Name:</b>
  <%= @product.name %>
</p>

<p>
  <b>Price:</b>
  <%= @product.price %>
</p>

<p>
  <b>Category:</b>
  <%= @product.category && @product.category.name %>
</p>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>